name: Nightly - GitHub Action Doc Test - Dynamic Matrix

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing dynamic matrix https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson"
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
