name: pull_request_playground

permissions:
  contents: read
  issues: write

on:
  pull_request:
    branches:
    - main
  issues:
    types:
    - opened
    - edited

jobs:
  test_edit_body:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context.payload)

          const isPR = context.payload.pull_request || context.payload.issue.pull_request
          await github.rest.issues.createComment({
            repo: context.repo.repo,
            owner: context.repo.owner,
            issue_number: context.issue.number,
            body: `
              event-name: ${context.eventName}
              action: ${context.action}
              pull_request: ${isPR ? 'Yes' : 'No'}
            `
          })